auth-server-url:  http://192.168.60.100:50100
security:
  oauth2:
    client:
      client-id: CrmSys
      client-secret: 123456
      access-token-uri: ${auth-server-url}/oauth/token
      user-authorization-uri: ${auth-server-url}/oauth/authorize
      scope: dipont
    resource:
      token-info-uri: ${auth-server-url}/oauth/check_token

server:
  port: 50200
  servlet:
    session:
      cookie:
        name: UISESSIONMEMBER
jwt:
  # 密匙key
  secret: 123456
